### PR TITLE
1.13 support

### PR DESCRIPTION
**Pull request by sgdc3**
Requires WorldGuard 7.0.0! (WG Api changed heavily)

### CODE REVIEW

**Comment by sgdc3** [comment]
@NoChanceSD

**Comment by NoChanceSD** [comment]
I would prefer to keep changed to pom files to a minimum. 
Also, do you know if WorldGuard is planning to add version 7 to their repo?

**Comment by sgdc3** [comment]
Yeah, but only after the release

**Comment by sgdc3** [comment]
What do you want to keep from the old pom, it was all messed up, is there anything in particular you need?

**Comment by sgdc3** [comment]
@NoChanceSD

**Comment by sgdc3** [comment]
@NoChanceSD bump

**Comment by sgdc3** [comment]
@NoChanceSD https://github.com/CodeMC/WorldGuardWrapper

**Pull request closed without merging**
