### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by EvilOlaf**
There are some problems in game with the German umlaute ä ü ö. 
Maybe have a look into that.

### CODE REVIEW

**Comment by NoChanceSD** [comment]
Thanks, do those problems happen with the latest build?

**Comment by EvilOlaf** [comment]
I tried a very recent dev build, but not sure about. I'll check that later.

**Comment by EvilOlaf** [comment]
Tested with current dev build 127.
http://www0.xup.in/exec/ximg.php?fid=10782364 
Second line the last word should be `ändern`. The `ä` is not displayed correctly. I am pretty sure this happens to the other umlaute ö and ü too, but did not especially test it.

**Comment by NoChanceSD** [comment]
Try changing the messages file encoding to UTF-8 if you have notepad++
Or delete the messages file and let it regenerate.

**Comment by EvilOlaf** [comment]
Works!

**Comment by NoChanceSD** [comment]
Cool, will merge this now

**Pull request merged**
